/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
  public static void main(String[] args) {
    Lesson[] lessons = new Lesson[10];
    java.util.Scanner keyboard = new java.util.Scanner(System.in);
    int i = 0;
    
    while (true) {
      Lesson lesson = new Lesson();
      System.out.print("번호? ");
      lesson.num = Integer.parseInt(keyboard.nextLine());
      System.out.print("수업명? ");
      lesson.className = keyboard.nextLine();
      System.out.print("수업내용? ");
      lesson.classContents = keyboard.nextLine();
      System.out.print("시작일? ");
      lesson.startDate = keyboard.nextLine();
      System.out.print("종료일? ");
      lesson.endDate = keyboard.nextLine();
      System.out.print("총수업시간? ");
      lesson.totalClassTime = Integer.parseInt(keyboard.nextLine());
      System.out.print("일수업시간? ");
      lesson.oneClassHour = Integer.parseInt(keyboard.nextLine());

      lessons[i] = lesson;

      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String cont = keyboard.nextLine();
      i++; 
      if (!cont.equalsIgnoreCase("Y")) {
        int start = 0;
        while (start < i) {
          System.out.printf("%-15s, %s ~ %s, %s\n", lessons[start].className, lessons[start].startDate, lessons[start].endDate, lessons[start].oneClassHour);
          start++;
        }
        keyboard.close();
        break;
      }
    }
    
  }
}