/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App {
  public static void main(String[] args) {

    int[] num = new int[100];
    String[] className = new String[100];
    String[] classContents = new String[100];
    String[] startDate = new String[100];
    String[] endDate = new String[100];
    int[] totalClassTime = new int[100];
    int[] oneClassHour = new int[100];

    int i = 0;
    int end = 0;
    
    while (true) {
      
      java.util.Scanner keyboard = new java.util.Scanner(System.in);
      System.out.print("번호? ");
      num[i] = Integer.parseInt(keyboard.nextLine());

      System.out.print("수업명? ");
      className[i] = keyboard.nextLine();

      System.out.print("수업내용? ");
      classContents[i] = keyboard.nextLine();

      System.out.print("시작일? ");
      startDate[i] = keyboard.nextLine();

      System.out.print("종료일? ");
      endDate[i] = keyboard.nextLine();

      System.out.print("총수업시간? ");
      totalClassTime[i] = Integer.parseInt(keyboard.nextLine());

      System.out.print("일수업시간? ");
      oneClassHour[i] = Integer.parseInt(keyboard.nextLine());
      System.out.println(i);


      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String cont = keyboard.nextLine();
      end++;
      i++;
      
      if (cont.equalsIgnoreCase("Y") || cont.equalsIgnoreCase("y") || cont.equalsIgnoreCase("\n")) {
        continue;
      } else if (!cont.equalsIgnoreCase("Y")) {
        int start = 0;
        while (start < end) {
          System.out.printf("%-15s, %s ~ %s, %s\n", className[start], startDate[start], endDate[start], oneClassHour[start]);
          start++;
        }
        break;
      }
      
    }
  }
}
