/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

public class App3 {
  public static void main(String[] args) {
    System.out.println("번호: 1");
    System.out.println("내용: 게시글입니다.");
    System.out.println("작성일: 2019-01-01");
    System.out.println("조회수: 0");
  }
}
