/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class App3 {
  public static void main(String[] args) {
    
    Scanner keyboard = new Scanner(System.in);
    List<Board> boards = new ArrayList<Board>();
    
    while (true) {
      
      System.out.print("번호? ");
      int no = Integer.parseInt(keyboard.nextLine());
      System.out.print("내용? ");
      String content = keyboard.nextLine();
      Board board = new Board(no, content);
      
      boards.add(board);
      
      System.out.print("\n계속 입력하시겠습니까?(Y/n) ");
      String cont = keyboard.nextLine();
      System.out.println();
      if (!cont.equalsIgnoreCase("y") && !cont.equals("")) {
        break;
      }
    }
    
    keyboard.close();
    for (int i = 0; i < boards.size(); i++) {
      boards.get(i).print();
    }
  }
}
