/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
  public static void main(String[] args) {

    final int LENTH = 100;

    Lesson[] lessons = new Lesson[LENTH];
    Scanner keyboard = new Scanner(System.in);

    int size = 0;

    while (size < LENTH) {
      Lesson lesson = new Lesson();

      System.out.print("번호? ");
      lesson.num = Integer.parseInt(keyboard.nextLine());
      System.out.print("수업명? ");
      lesson.className = keyboard.nextLine();
      System.out.print("수업내용? ");
      lesson.classContents = keyboard.nextLine();
      System.out.print("시작일? ");
      lesson.startDate = Date.valueOf(keyboard.nextLine());
      System.out.print("종료일? ");
      lesson.endDate = Date.valueOf(keyboard.nextLine());
      System.out.print("총수업시간? ");
      lesson.totalClassTime = Integer.parseInt(keyboard.nextLine());
      System.out.print("일수업시간? ");
      lesson.oneClassHour = Integer.parseInt(keyboard.nextLine());

      lessons[size] = lesson;

      size++; 
      
      System.out.println();
      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String cont = keyboard.nextLine();

      if (!cont.equalsIgnoreCase("Y") && !cont.equals("")) break;
    }
    
    keyboard.close();
    
    System.out.println();
    
    for (int i = 0; i < size; i++) {
      System.out.printf("%-15s, %s ~ %s, %s\n", 
          lessons[i].className, lessons[i].startDate, lessons[i].endDate, lessons[i].oneClassHour);
    }
  }
}