/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.lms;

import java.util.Date;
import java.util.Scanner;

public class App2 {
  public static void main(String[] args) {
    Member[] Members = new Member[10];
    Scanner keyboard = new Scanner(System.in);
    int i = 0;
    while (true) {
      System.out.print("번호? ");
      int no = Integer.parseInt(keyboard.nextLine());
      System.out.print("이름? ");
      String name = keyboard.nextLine();
      System.out.print("이메일? ");
      String email = keyboard.nextLine();
      System.out.print("암호? ");
      String password = keyboard.nextLine();
      System.out.print("사진? ");
      String photo = keyboard.nextLine();
      System.out.print("전화? ");
      String tel = keyboard.nextLine();
      
      Member member = new Member(no, name, email, password, photo, tel);
      member.createdDate = new Date(System.currentTimeMillis());
      Members[i] = member;

      System.out.println();
      System.out.print("계속 입력하시겠습니까?(Y/n) ");
      String cont = keyboard.nextLine();
      i++;
      System.out.println();
      if (!cont.equalsIgnoreCase("Y")) {
        int start = 0;
        while (start < i) {
          Members[start].print();
          start++;
        }
        keyboard.close();
        break;
      }
    }
  }
}
